spring.application.name=gestorback
# JWT settings (set JWT_SECRET as environment variable)
jwt.expiration=3600000

# Hibernate
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# h2
spring.datasource.url=jdbc:h2:mem:gestordb
spring.h2.console.enabled=true

